### ISSUE TITLE
Update Parsedown version

### ISSUE THREAD

**Issue by ghost** [itpatrol/parsedown_filter#1]
The version of Parsedown included in this module is quite old.

One thing I noticed that they've fixed in a more recent version upstream is numbered lists starting at a value other than 1.

E.g.:
```
4. Blah
5. Yada
```
This'd be nice to have in this module.

https://github.com/erusev/parsedown/releases/tag/1.7.3 looks to be the most recent, stable release...

**Comment by ghost** [comment]
Made a [PR](https://github.com/backdrop-contrib/parsedown_filter/pull/2) that updates Parsedown to v1.7.3.

**Comment by yorkshire-pudding** [comment]
1.7.4 is the current latest. Added PR for that and to update Parsedown Extra to 0.8.1
