### ISSUE TITLE
Add maintainer

### ISSUE THREAD

**Issue by yorkshire-pudding** [itpatrol/parsedown_filter#5]
Hi @Gormartsen - I'd like to help (or take over) maintaining this module as I like how it works once I've updated to the latest versions.

Let me know which you would prefer and I'll create a PR accordingly.

**Comment by jenlampton** [comment]
I've merged your PR, and granted you admin access to the repository. Should @Gormartsen return and wish to participate, please consider adding him back to the project. Thank you for offering to contribute!
